'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import {products} from './data';
export type Role='buyer'|'seller'|'admin'; type Cart=Record<string,number>; type Order={id:string;status:string;total:number;createdAt:string;items:{id:string;qty:number}[]};
type ShopState={cart:Cart;user:string|null;role:Role|null;ready:boolean;points:number;orders:Order[];favorites:string[];count:number;items:{product:(typeof products)[number];qty:number}[];add:(id:string,n?:number)=>void;remove:(id:string)=>void;setCart:React.Dispatch<React.SetStateAction<Cart>>;setUser:(u:string|null,role?:Role|null)=>void;toggleFavorite:(id:string)=>void;createOrder:(discount?:number)=>string};
const C=createContext<ShopState|null>(null);
export function ShopProvider({children}:{children:React.ReactNode}){const[cart,setCart]=useState<Cart>({});const[user,setUserState]=useState<string|null>(null);const[role,setRole]=useState<Role|null>(null);const[points,setPoints]=useState(320);const[orders,setOrders]=useState<Order[]>([]);const[favorites,setFavorites]=useState<string[]>([]);const[ready,setReady]=useState(false);
useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('noma-cart')||'{}'));setUserState(localStorage.getItem('noma-user'));setRole((localStorage.getItem('noma-role') as Role)||null);setPoints(Number(localStorage.getItem('noma-points')||320));setOrders(JSON.parse(localStorage.getItem('noma-orders')||'[]'));setFavorites(JSON.parse(localStorage.getItem('noma-favorites')||'[]'))}finally{setReady(true)}},[]);
useEffect(()=>{if(ready){localStorage.setItem('noma-cart',JSON.stringify(cart));localStorage.setItem('noma-orders',JSON.stringify(orders));localStorage.setItem('noma-favorites',JSON.stringify(favorites));localStorage.setItem('noma-points',String(points))}},[cart,orders,favorites,points,ready]);
const state=useMemo<ShopState>(()=>{const items=Object.entries(cart).map(([id,qty])=>({product:products.find(p=>p.id===id)!,qty})).filter(x=>x.product);return {cart,user,role,ready,points,orders,favorites,items,count:Object.values(cart).reduce((a,b)=>a+b,0),setCart,add:(id,n=1)=>setCart(c=>({...c,[id]:(c[id]||0)+n})),remove:(id)=>setCart(c=>{const next={...c};delete next[id];return next}),setUser:(u,r=null)=>{setUserState(u);setRole(r);u?localStorage.setItem('noma-user',u):localStorage.removeItem('noma-user');r?localStorage.setItem('noma-role',r):localStorage.removeItem('noma-role')},toggleFavorite:(id)=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]),createOrder:(discount=0)=>{const id=`NM${Date.now().toString().slice(-8)}`;const total=Math.max(0,items.reduce((s,x)=>s+x.product.price*x.qty,0)-discount);setOrders(v=>[{id,status:'待发货',total,createdAt:new Date().toLocaleDateString('zh-CN'),items:items.map(x=>({id:x.product.id,qty:x.qty}))},...v]);setPoints(p=>p+Math.floor(total/10));setCart({});return id}}},[cart,user,role,ready,orders,favorites,points]);return <C.Provider value={state}>{children}</C.Provider>}
export const useShop=()=>{const value=useContext(C);if(!value)throw new Error('ShopProvider missing');return value};
